### ISSUE TITLE
Distro agnostic/systemd install.sh

### ISSUE THREAD

**Issue by Justinzobel** [lxc-webpanel/lxc-webpanel.github.com#6]
Got bored, decided to make the install script distro agnostic (in my limited bash) and provide a systemd startup script.
# !/bin/bash

echo ' _     __   _______  __          __  _       _____                 _ '
echo '| |    \ \ / / ____| \ \        / / | |     |  __ \               | |'
echo '| |     \ V / |       \ \  /\  / /**| |**   | |**) |_ _ _ __   **_| |'
echo "| |      > <| |        \ \/  \/ / _ \ '_ \  |  ___/ _` | '_ \ / _ \ |"
echo '| |**** / . \ |____     \  /\  /  **/ |_) | | |  | (_| | | | |  **/ |'
echo '|__****/_/ \______|     \/  \/ _**|_.**/  |_|   __,_|_| |_|___|_|'
echo -e '\n\nAutomatic installer\n'

if [[ "$UID" -ne "0" ]];then
    echo 'You must be root to install LXC Web Panel !'
    exit
fi
### BEGIN PROGRAM

red="\e[31m"
green="\e[0;92m"
white="\e[0m"

INSTALL_DIR='/srv/lwp'

if [[ -d "$INSTALL_DIR" ]];then
    echo "You already have LXC Web Panel installed. You'll need to remove $INSTALL_DIR if you want to install"
    exit 1
fi

echo 'Checking for requirements...'
if [[ ! -f /usr/bin/python2 ]]
    then
        echo -e "${red}-${white}Python 2 missing, please install."
        exit 1
    else
        echo -e "${green}+${white}Python 2 installed."
fi
if [[ ! -f /usr/bin/git ]]
    then
        echo -e "${red}-${white}Git missing, please install."
        exit 1
    else
        echo -e "${green}+${white}Git installed."
fi
if [[ ! -f /usr/bin/pip ]]
    then
        echo -e "${red}-${white}Pip missing, please install."
        exit 1
    else
        echo -e "${green}+${white}Pip installed."
        python -c 'import flask' &> /dev/null || {
        echo '| + Flask Python...'
        pip install flask==0.9 2> /dev/null
        }

fi

git clone -b 0.2 https://github.com/lxc-webpanel/LXC-Web-Panel.git "$INSTALL_DIR"

echo -e '\nInstallation complete!\n\n'

echo 'Adding start script...'

cat > '/srv/lwp/start.sh' <<EOF
# !/bin/bash

cd /srv/lwp
/usr/bin/python /srv/lwp/lwp.py
EOF

chmod +x /srv/lwp/start.sh

echo 'Adding lwp.service file...'

cat > '/etc/systemd/system/lwp.service' <<EOF
[Unit]
Description=LXC Web Panel
After=syslog.target network.target

[Service]
User=root
RootDirectory=/srv/lwp/
RootDirectoryStartOnly=yes
ExecStart=/usr/bin/python $INSTALL_DIR/lwp.py
PIDFile=/var/run/lwp.pid

[Install]
WantedBy=multi-user.target
EOF

mkdir -p /etc/lxc/auto
chmod +x /srv/lwp/lwp.py
systemctl enable lwp.service
systemctl start lwp.service
echo 'Done'
echo 'Connect you on http://localhost:5000/'

**Comment by PhilipDeegan** [comment]
Maybe put it in a gist as the markdown is messing with the text.
