### ISSUE TITLE
Internal Server Error - webpanel on ubuntu 16.04 container

### ISSUE THREAD

**Issue by heiniovason** [lxc-webpanel/lxc-webpanel.github.com#8]
After login I get this message:

_"Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."_

Don't really know where to go from here :) The LXC container is of type **Ubuntu Server 16.04.2 LTS**

**Comment by ElieDeloumeau** [comment]
Wrong repo
Compatible with LXC 0.7 to 0.9
